export type EvmChainConfig = {
  chainId: number;
  name: string;
  shortName: string;
  symbol: string;
  logoSlug: string;
  explorerUrl: string;
  coingeckoId?: string;
  popular?: boolean;
  gasOracleAvailable?: boolean;
};

export const evmChains = [
  {
    chainId: 1,
    name: "Ethereum",
    shortName: "ETH",
    symbol: "ETH",
    logoSlug: "ethereum",
    explorerUrl: "https://etherscan.io",
    coingeckoId: "ethereum",
    popular: true,
  },
  {
    chainId: 56,
    name: "BNB Smart Chain",
    shortName: "BNB",
    symbol: "BNB",
    logoSlug: "bnb",
    explorerUrl: "https://bscscan.com",
    coingeckoId: "binancecoin",
    popular: true,
    gasOracleAvailable: false,
  },
  {
    chainId: 137,
    name: "Polygon",
    shortName: "POL",
    symbol: "POL",
    logoSlug: "polygon",
    explorerUrl: "https://polygonscan.com",
    coingeckoId: "polygon-ecosystem-token",
    popular: true,
  },
  {
    chainId: 42161,
    name: "Arbitrum One",
    shortName: "ARB",
    symbol: "ETH",
    logoSlug: "arbitrum",
    explorerUrl: "https://arbiscan.io",
    coingeckoId: "ethereum",
    popular: true,
    gasOracleAvailable: false,
  },
  {
    chainId: 10,
    name: "Optimism",
    shortName: "OP",
    symbol: "ETH",
    logoSlug: "optimism",
    explorerUrl: "https://optimistic.etherscan.io",
    coingeckoId: "ethereum",
    popular: true,
    gasOracleAvailable: false,
  },
  {
    chainId: 8453,
    name: "Base",
    shortName: "BASE",
    symbol: "ETH",
    logoSlug: "base",
    explorerUrl: "https://basescan.org",
    coingeckoId: "ethereum",
    popular: true,
    gasOracleAvailable: false,
  },
  {
    chainId: 43114,
    name: "Avalanche C-Chain",
    shortName: "AVAX",
    symbol: "AVAX",
    logoSlug: "avalanche",
    explorerUrl: "https://snowtrace.io",
    coingeckoId: "avalanche-2",
    popular: true,
    gasOracleAvailable: false,
  },
  {
    chainId: 324,
    name: "zkSync Era",
    shortName: "ZK",
    symbol: "ETH",
    logoSlug: "zksync",
    explorerUrl: "https://era.zksync.network",
    coingeckoId: "ethereum",
    popular: true,
    gasOracleAvailable: false,
  },
  {
    chainId: 59144,
    name: "Linea",
    shortName: "LINEA",
    symbol: "ETH",
    logoSlug: "linea",
    explorerUrl: "https://lineascan.build",
    coingeckoId: "ethereum",
    popular: true,
    gasOracleAvailable: false,
  },
  {
    chainId: 534352,
    name: "Scroll",
    shortName: "SCR",
    symbol: "ETH",
    logoSlug: "scroll",
    explorerUrl: "https://scrollscan.com",
    coingeckoId: "ethereum",
    popular: true,
    gasOracleAvailable: false,
  },
  {
    chainId: 100,
    name: "Gnosis",
    shortName: "GNO",
    symbol: "xDAI",
    logoSlug: "gnosis",
    explorerUrl: "https://gnosisscan.io",
    coingeckoId: "xdai",
  },
  {
    chainId: 250,
    name: "Fantom",
    shortName: "FTM",
    symbol: "FTM",
    logoSlug: "fantom",
    explorerUrl: "https://ftmscan.com",
    coingeckoId: "fantom",
    gasOracleAvailable: false,
  },
  {
    chainId: 42220,
    name: "Celo",
    shortName: "CELO",
    symbol: "CELO",
    logoSlug: "celo",
    explorerUrl: "https://celoscan.io",
    coingeckoId: "celo",
  },
  {
    chainId: 1284,
    name: "Moonbeam",
    shortName: "GLMR",
    symbol: "GLMR",
    logoSlug: "moonbeam",
    explorerUrl: "https://moonscan.io",
    coingeckoId: "moonbeam",
  },
  {
    chainId: 5000,
    name: "Mantle",
    shortName: "MNT",
    symbol: "MNT",
    logoSlug: "mantle",
    explorerUrl: "https://mantlescan.xyz",
    coingeckoId: "mantle",
    popular: true,
    gasOracleAvailable: false,
  },
  {
    chainId: 81457,
    name: "Blast",
    shortName: "BLAST",
    symbol: "ETH",
    logoSlug: "blast",
    explorerUrl: "https://blastscan.io",
    coingeckoId: "ethereum",
    gasOracleAvailable: false,
  },
  {
    chainId: 204,
    name: "opBNB",
    shortName: "opBNB",
    symbol: "BNB",
    logoSlug: "opbnb",
    explorerUrl: "https://opbnb.bscscan.com",
    coingeckoId: "binancecoin",
    gasOracleAvailable: false,
  },
  {
    chainId: 25,
    name: "Cronos",
    shortName: "CRO",
    symbol: "CRO",
    logoSlug: "cronos",
    explorerUrl: "https://cronoscan.com",
    coingeckoId: "crypto-com-chain",
    gasOracleAvailable: false,
  },
  {
    chainId: 130,
    name: "Unichain",
    shortName: "UNI",
    symbol: "ETH",
    logoSlug: "unichain",
    explorerUrl: "https://uniscan.xyz",
    coingeckoId: "ethereum",
    gasOracleAvailable: false,
  },
  {
    chainId: 480,
    name: "World Chain",
    shortName: "WORLD",
    symbol: "ETH",
    logoSlug: "world-chain",
    explorerUrl: "https://worldscan.org",
    coingeckoId: "ethereum",
    gasOracleAvailable: false,
  },
  {
    chainId: 146,
    name: "Sonic",
    shortName: "S",
    symbol: "S",
    logoSlug: "sonic",
    explorerUrl: "https://sonicscan.org",
    coingeckoId: "sonic-3",
    gasOracleAvailable: false,
  },
  {
    chainId: 80094,
    name: "Berachain",
    shortName: "BERA",
    symbol: "BERA",
    logoSlug: "berachain",
    explorerUrl: "https://berascan.com",
    coingeckoId: "berachain-bera",
    gasOracleAvailable: false,
  },
] satisfies EvmChainConfig[];

export const popularEvmChains = evmChains.filter((chain) => chain.popular);
export const gasOracleEvmChains = evmChains.filter((chain) => chain.gasOracleAvailable !== false);
